--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+1)
-- Dumped by pg_dump version 16.4

-- Started on 2024-10-03 09:09:32 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 16493)
-- Name: days; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.days (
    id integer NOT NULL,
    name integer NOT NULL
);


ALTER TABLE public.days OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16492)
-- Name: days_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.days ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.days_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16513)
-- Name: disciplines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.disciplines (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    id_teacher integer NOT NULL
);


ALTER TABLE public.disciplines OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16512)
-- Name: disciplines_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.disciplines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disciplines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16468)
-- Name: faculties; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.faculties (
    id integer NOT NULL,
    title character varying(300) NOT NULL
);


ALTER TABLE public.faculties OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16467)
-- Name: faculties_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.faculties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faculties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16476)
-- Name: groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.groups (
    id integer NOT NULL,
    title character varying(20) NOT NULL,
    id_faculty integer NOT NULL
);


ALTER TABLE public.groups OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16475)
-- Name: groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16526)
-- Name: rooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rooms (
    id integer NOT NULL,
    num integer NOT NULL
);


ALTER TABLE public.rooms OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16525)
-- Name: rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16531)
-- Name: shedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shedule (
    id integer NOT NULL,
    id_time integer NOT NULL,
    id_discipline character varying NOT NULL,
    id_teacher character varying NOT NULL,
    id_room integer NOT NULL,
    id_group character varying NOT NULL,
    id_faculty character varying NOT NULL,
    id_day integer NOT NULL
);


ALTER TABLE public.shedule OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16499)
-- Name: students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.students (
    id integer NOT NULL,
    surname character varying(50) NOT NULL,
    name character varying(50) NOT NULL,
    patr character varying(50) NOT NULL,
    "[group]" character varying NOT NULL
);


ALTER TABLE public.students OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16498)
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16520)
-- Name: teachers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teachers (
    id integer NOT NULL,
    fio character varying(300) NOT NULL
);


ALTER TABLE public.teachers OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16519)
-- Name: teachers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teachers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teachers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16507)
-- Name: times; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.times (
    id integer NOT NULL,
    "time" integer NOT NULL
);


ALTER TABLE public.times OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16506)
-- Name: times_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.times ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.times_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16487)
-- Name: weeks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.weeks (
    num integer NOT NULL,
    dt_beg integer NOT NULL,
    dt_end integer NOT NULL
);


ALTER TABLE public.weeks OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16486)
-- Name: weeks_num_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.weeks ALTER COLUMN num ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weeks_num_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3422 (class 0 OID 16493)
-- Dependencies: 222
-- Data for Name: days; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3428 (class 0 OID 16513)
-- Dependencies: 228
-- Data for Name: disciplines; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3416 (class 0 OID 16468)
-- Dependencies: 216
-- Data for Name: faculties; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.faculties VALUES (1, 'Факультет мехатроники и автоматизации');
INSERT INTO public.faculties VALUES (2, 'Факультет бизнеса');
INSERT INTO public.faculties VALUES (3, 'Факультет автоматики и вычислительной техники');
INSERT INTO public.faculties VALUES (4, 'Факультет радиотехники и электроники');
INSERT INTO public.faculties VALUES (5, 'Механико-технологический факультет');
INSERT INTO public.faculties VALUES (6, 'Факультет летательных аппаратов');
INSERT INTO public.faculties VALUES (7, 'Факультет прикладной математики и информатики');
INSERT INTO public.faculties VALUES (8, 'Физико-технический факультет');
INSERT INTO public.faculties VALUES (9, 'Факультет энергетики');
INSERT INTO public.faculties VALUES (10, 'Факультет гуманитарного образования');
INSERT INTO public.faculties VALUES (13, 'Заочное отделение');
INSERT INTO public.faculties VALUES (21, 'Институт социальных технологий');


--
-- TOC entry 3418 (class 0 OID 16476)
-- Dependencies: 218
-- Data for Name: groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.groups VALUES (1, 'АА-46', 3);
INSERT INTO public.groups VALUES (2, 'АА-47', 3);
INSERT INTO public.groups VALUES (3, 'АБс-424', 3);
INSERT INTO public.groups VALUES (4, 'АБс-425', 3);
INSERT INTO public.groups VALUES (5, 'АБс-426', 3);
INSERT INTO public.groups VALUES (6, 'АБс-427', 3);
INSERT INTO public.groups VALUES (7, 'АБ-420', 3);
INSERT INTO public.groups VALUES (8, 'АБ-421', 3);
INSERT INTO public.groups VALUES (9, 'АБ-422', 3);
INSERT INTO public.groups VALUES (10, 'АВТ-408', 3);
INSERT INTO public.groups VALUES (11, 'АВТ-409', 3);
INSERT INTO public.groups VALUES (12, 'АВТ-410', 3);
INSERT INTO public.groups VALUES (13, 'АВТ-412', 3);
INSERT INTO public.groups VALUES (14, 'АВТ-413', 3);
INSERT INTO public.groups VALUES (15, 'АВТ-414', 3);
INSERT INTO public.groups VALUES (16, 'АВТ-418', 3);
INSERT INTO public.groups VALUES (17, 'АВТ-419', 3);
INSERT INTO public.groups VALUES (18, 'АВТ-441', 3);
INSERT INTO public.groups VALUES (19, 'АВТ-442', 3);
INSERT INTO public.groups VALUES (20, 'АВТ-443', 3);
INSERT INTO public.groups VALUES (21, 'АИ-42', 3);
INSERT INTO public.groups VALUES (22, 'АО-41', 3);
INSERT INTO public.groups VALUES (23, 'АО-42', 3);
INSERT INTO public.groups VALUES (24, 'АП-426', 3);
INSERT INTO public.groups VALUES (25, 'АП-427', 3);
INSERT INTO public.groups VALUES (26, 'АТ-43', 3);
INSERT INTO public.groups VALUES (27, 'АТ-44', 3);
INSERT INTO public.groups VALUES (28, 'АТ-45', 3);
INSERT INTO public.groups VALUES (29, 'АА-36', 3);
INSERT INTO public.groups VALUES (30, 'АА-37', 3);
INSERT INTO public.groups VALUES (31, 'АБс-322', 3);
INSERT INTO public.groups VALUES (32, 'АБс-323', 3);
INSERT INTO public.groups VALUES (33, 'АБс-324', 3);
INSERT INTO public.groups VALUES (34, 'АБ-320', 3);
INSERT INTO public.groups VALUES (35, 'АБ-321', 3);
INSERT INTO public.groups VALUES (36, 'АВТ-308', 3);
INSERT INTO public.groups VALUES (37, 'АВТ-309', 3);
INSERT INTO public.groups VALUES (38, 'АВТ-310', 3);
INSERT INTO public.groups VALUES (39, 'АВТ-312', 3);
INSERT INTO public.groups VALUES (40, 'АВТ-313', 3);
INSERT INTO public.groups VALUES (41, 'АВТ-314', 3);
INSERT INTO public.groups VALUES (42, 'АВТ-318', 3);
INSERT INTO public.groups VALUES (43, 'АВТ-319', 3);
INSERT INTO public.groups VALUES (44, 'АВТ-341', 3);
INSERT INTO public.groups VALUES (45, 'АВТ-342', 3);
INSERT INTO public.groups VALUES (46, 'АВТ-343', 3);
INSERT INTO public.groups VALUES (47, 'АИ-32', 3);
INSERT INTO public.groups VALUES (48, 'АО-31', 3);
INSERT INTO public.groups VALUES (49, 'АО-32', 3);
INSERT INTO public.groups VALUES (50, 'АП-326', 3);
INSERT INTO public.groups VALUES (51, 'АП-327', 3);
INSERT INTO public.groups VALUES (52, 'АТ-33', 3);
INSERT INTO public.groups VALUES (53, 'АТ-34', 3);
INSERT INTO public.groups VALUES (54, 'АА-26', 3);
INSERT INTO public.groups VALUES (55, 'АА-27', 3);
INSERT INTO public.groups VALUES (56, 'АБс-222', 3);
INSERT INTO public.groups VALUES (57, 'АБс-223', 3);
INSERT INTO public.groups VALUES (58, 'АБ-220', 3);
INSERT INTO public.groups VALUES (59, 'АБ-221', 3);
INSERT INTO public.groups VALUES (60, 'АВТ-208', 3);
INSERT INTO public.groups VALUES (61, 'АВТ-209', 3);
INSERT INTO public.groups VALUES (62, 'АВТ-210', 3);
INSERT INTO public.groups VALUES (63, 'АВТ-213', 3);
INSERT INTO public.groups VALUES (64, 'АВТ-214', 3);
INSERT INTO public.groups VALUES (65, 'АВТ-218', 3);
INSERT INTO public.groups VALUES (66, 'АВТ-219', 3);
INSERT INTO public.groups VALUES (67, 'АВТ-241', 3);
INSERT INTO public.groups VALUES (68, 'АВТ-242', 3);
INSERT INTO public.groups VALUES (69, 'АВТ-243', 3);
INSERT INTO public.groups VALUES (70, 'АИ-22', 3);
INSERT INTO public.groups VALUES (71, 'АО-22', 3);
INSERT INTO public.groups VALUES (72, 'АП-226', 3);
INSERT INTO public.groups VALUES (73, 'АП-227', 3);
INSERT INTO public.groups VALUES (74, 'АТ-23', 3);
INSERT INTO public.groups VALUES (75, 'АТ-24', 3);
INSERT INTO public.groups VALUES (76, 'АА-16', 3);
INSERT INTO public.groups VALUES (77, 'АБс-123', 3);
INSERT INTO public.groups VALUES (78, 'АБ-120', 3);
INSERT INTO public.groups VALUES (79, 'АВТ-108', 3);
INSERT INTO public.groups VALUES (80, 'АВТ-109', 3);
INSERT INTO public.groups VALUES (81, 'АВТ-110', 3);
INSERT INTO public.groups VALUES (82, 'АВТ-113', 3);
INSERT INTO public.groups VALUES (83, 'АВТ-114', 3);
INSERT INTO public.groups VALUES (84, 'АВТ-118', 3);
INSERT INTO public.groups VALUES (85, 'АВТ-119', 3);
INSERT INTO public.groups VALUES (86, 'АВТ-141', 3);
INSERT INTO public.groups VALUES (87, 'АВТ-143', 3);
INSERT INTO public.groups VALUES (88, 'АИ-12', 3);
INSERT INTO public.groups VALUES (89, 'АО-12', 3);
INSERT INTO public.groups VALUES (90, 'АП-126', 3);
INSERT INTO public.groups VALUES (91, 'АТ-13', 3);
INSERT INTO public.groups VALUES (92, 'АТ-14', 3);
INSERT INTO public.groups VALUES (93, 'АБс-022', 3);
INSERT INTO public.groups VALUES (94, 'ААМ-24', 3);
INSERT INTO public.groups VALUES (95, 'АБМ-24', 3);
INSERT INTO public.groups VALUES (96, 'АЗМ-24', 3);
INSERT INTO public.groups VALUES (97, 'АИМ-24', 3);
INSERT INTO public.groups VALUES (98, 'АИСМ-24', 3);
INSERT INTO public.groups VALUES (99, 'АММ2-24', 3);
INSERT INTO public.groups VALUES (100, 'АММ-24', 3);
INSERT INTO public.groups VALUES (101, 'АОМ-24', 3);
INSERT INTO public.groups VALUES (102, 'АПИМ2-24', 3);
INSERT INTO public.groups VALUES (103, 'АПИМ-24', 3);
INSERT INTO public.groups VALUES (104, 'АПМ-24', 3);
INSERT INTO public.groups VALUES (105, 'АСМ2-24', 3);
INSERT INTO public.groups VALUES (106, 'АСМ-24', 3);
INSERT INTO public.groups VALUES (107, 'ВШ6-41', 3);
INSERT INTO public.groups VALUES (108, 'ААМ-23', 3);
INSERT INTO public.groups VALUES (109, 'АПИМ2-23', 3);
INSERT INTO public.groups VALUES (110, 'АПИМ-23', 3);
INSERT INTO public.groups VALUES (111, 'АПМ-23', 3);
INSERT INTO public.groups VALUES (112, 'АСМ-23', 3);
INSERT INTO public.groups VALUES (113, 'SD-43', 6);
INSERT INTO public.groups VALUES (114, 'ГС-41', 6);
INSERT INTO public.groups VALUES (115, 'МА-41', 6);
INSERT INTO public.groups VALUES (116, 'МБ-41', 6);
INSERT INTO public.groups VALUES (117, 'МВ-41', 6);
INSERT INTO public.groups VALUES (118, 'МР-41', 6);
INSERT INTO public.groups VALUES (119, 'ПС-41', 6);
INSERT INTO public.groups VALUES (120, 'СА-41', 6);
INSERT INTO public.groups VALUES (121, 'СД-41', 6);
INSERT INTO public.groups VALUES (122, 'СЭ-41', 6);
INSERT INTO public.groups VALUES (123, 'С-41', 6);
INSERT INTO public.groups VALUES (124, 'С-42', 6);
INSERT INTO public.groups VALUES (125, 'ТС-41', 6);
INSERT INTO public.groups VALUES (126, 'ЭП-41', 6);
INSERT INTO public.groups VALUES (127, 'ГС-31', 6);
INSERT INTO public.groups VALUES (128, 'ГС-32', 6);
INSERT INTO public.groups VALUES (129, 'МА-31', 6);
INSERT INTO public.groups VALUES (130, 'МБ-31', 6);
INSERT INTO public.groups VALUES (131, 'МВ-31', 6);
INSERT INTO public.groups VALUES (132, 'МР-31', 6);
INSERT INTO public.groups VALUES (133, 'ПС-31', 6);
INSERT INTO public.groups VALUES (134, 'СА-31', 6);
INSERT INTO public.groups VALUES (135, 'СД-31', 6);
INSERT INTO public.groups VALUES (136, 'СЭ-31', 6);
INSERT INTO public.groups VALUES (137, 'С-31', 6);
INSERT INTO public.groups VALUES (138, 'С-32', 6);
INSERT INTO public.groups VALUES (139, 'ТС-31', 6);
INSERT INTO public.groups VALUES (140, 'ЭП-31', 6);
INSERT INTO public.groups VALUES (141, 'ГС-21', 6);
INSERT INTO public.groups VALUES (142, 'МА-21', 6);
INSERT INTO public.groups VALUES (143, 'МБ-21', 6);
INSERT INTO public.groups VALUES (144, 'МВ-21', 6);
INSERT INTO public.groups VALUES (145, 'МР-21', 6);
INSERT INTO public.groups VALUES (146, 'ПС-21', 6);
INSERT INTO public.groups VALUES (147, 'СА-21', 6);
INSERT INTO public.groups VALUES (148, 'СД-21', 6);
INSERT INTO public.groups VALUES (149, 'СЭ-21', 6);
INSERT INTO public.groups VALUES (150, 'С-21', 6);
INSERT INTO public.groups VALUES (151, 'С-22', 6);
INSERT INTO public.groups VALUES (152, 'ТС-21', 6);
INSERT INTO public.groups VALUES (153, 'ЭП-21', 6);
INSERT INTO public.groups VALUES (154, 'ГС-11', 6);
INSERT INTO public.groups VALUES (155, 'МА-11', 6);
INSERT INTO public.groups VALUES (156, 'МБ-11', 6);
INSERT INTO public.groups VALUES (157, 'МВ-11', 6);
INSERT INTO public.groups VALUES (158, 'МР-11', 6);
INSERT INTO public.groups VALUES (159, 'ПС-11', 6);
INSERT INTO public.groups VALUES (160, 'СА-11', 6);
INSERT INTO public.groups VALUES (161, 'СД-11', 6);
INSERT INTO public.groups VALUES (162, 'СЭ-11', 6);
INSERT INTO public.groups VALUES (163, 'С-11', 6);
INSERT INTO public.groups VALUES (164, 'С-12', 6);
INSERT INTO public.groups VALUES (165, 'ТС-11', 6);
INSERT INTO public.groups VALUES (166, 'ГС-01', 6);
INSERT INTO public.groups VALUES (167, 'МА-01', 6);
INSERT INTO public.groups VALUES (168, 'МВ-01', 6);
INSERT INTO public.groups VALUES (169, 'АУМ-41', 6);
INSERT INTO public.groups VALUES (170, 'ВШ4-41', 6);
INSERT INTO public.groups VALUES (171, 'ВШ5-41', 6);
INSERT INTO public.groups VALUES (172, 'ГСМ-41', 6);
INSERT INTO public.groups VALUES (173, 'МБМ-41', 6);
INSERT INTO public.groups VALUES (174, 'ПСМ-41', 6);
INSERT INTO public.groups VALUES (175, 'САМ-41', 6);
INSERT INTO public.groups VALUES (176, 'СМ-41', 6);
INSERT INTO public.groups VALUES (177, 'СЭМ-41', 6);
INSERT INTO public.groups VALUES (178, 'АУМ-31', 6);
INSERT INTO public.groups VALUES (179, 'ГСМ-31', 6);
INSERT INTO public.groups VALUES (180, 'ПСМ-31', 6);
INSERT INTO public.groups VALUES (181, 'САМ-31', 6);
INSERT INTO public.groups VALUES (182, 'СДМ-31', 6);
INSERT INTO public.groups VALUES (183, 'СМ-31', 6);
INSERT INTO public.groups VALUES (184, 'СЭМ-31', 6);
INSERT INTO public.groups VALUES (185, 'ТСМ-31', 6);
INSERT INTO public.groups VALUES (186, 'КМ-124', 5);
INSERT INTO public.groups VALUES (187, 'КП-124', 5);
INSERT INTO public.groups VALUES (188, 'КХ-124', 5);
INSERT INTO public.groups VALUES (189, 'ММ-124', 5);
INSERT INTO public.groups VALUES (190, 'МтР-124', 5);
INSERT INTO public.groups VALUES (191, 'НТ-124', 5);
INSERT INTO public.groups VALUES (192, 'ТА-124', 5);
INSERT INTO public.groups VALUES (193, 'ТМ-124', 5);
INSERT INTO public.groups VALUES (194, 'ТХ-124', 5);
INSERT INTO public.groups VALUES (195, 'ХТ-124', 5);
INSERT INTO public.groups VALUES (196, 'ЦТК-124', 5);
INSERT INTO public.groups VALUES (197, 'КМ-123', 5);
INSERT INTO public.groups VALUES (198, 'КП-123', 5);
INSERT INTO public.groups VALUES (199, 'ММ-123', 5);
INSERT INTO public.groups VALUES (200, 'МтР-123', 5);
INSERT INTO public.groups VALUES (201, 'НТ-123', 5);
INSERT INTO public.groups VALUES (202, 'ТА-123', 5);
INSERT INTO public.groups VALUES (203, 'ТМ-123', 5);
INSERT INTO public.groups VALUES (204, 'ТХ-123', 5);
INSERT INTO public.groups VALUES (205, 'ХТ-123', 5);
INSERT INTO public.groups VALUES (206, 'ХТ-223', 5);
INSERT INTO public.groups VALUES (207, 'ЦТК-123', 5);
INSERT INTO public.groups VALUES (208, 'КМ-122', 5);
INSERT INTO public.groups VALUES (209, 'КП-122', 5);
INSERT INTO public.groups VALUES (210, 'ММ-122', 5);
INSERT INTO public.groups VALUES (211, 'МП-122', 5);
INSERT INTO public.groups VALUES (212, 'МтР-122', 5);
INSERT INTO public.groups VALUES (213, 'НТ-122', 5);
INSERT INTO public.groups VALUES (214, 'ТА-122', 5);
INSERT INTO public.groups VALUES (215, 'ТМ-122', 5);
INSERT INTO public.groups VALUES (216, 'ТХ-122', 5);
INSERT INTO public.groups VALUES (217, 'ХТ-122', 5);
INSERT INTO public.groups VALUES (218, 'ХТ-222', 5);
INSERT INTO public.groups VALUES (219, 'КМ-121', 5);
INSERT INTO public.groups VALUES (220, 'КП-121', 5);
INSERT INTO public.groups VALUES (221, 'ММ-121', 5);
INSERT INTO public.groups VALUES (222, 'МтР-121', 5);
INSERT INTO public.groups VALUES (223, 'НТ-121', 5);
INSERT INTO public.groups VALUES (224, 'ТА-121', 5);
INSERT INTO public.groups VALUES (225, 'ТМ-121', 5);
INSERT INTO public.groups VALUES (226, 'ТХ-121', 5);
INSERT INTO public.groups VALUES (227, 'ХТ-121', 5);
INSERT INTO public.groups VALUES (228, 'ХТ-221', 5);
INSERT INTO public.groups VALUES (229, 'ВШ3-41', 5);
INSERT INTO public.groups VALUES (230, 'Маг-124', 5);
INSERT INTO public.groups VALUES (231, 'Маг-424', 5);
INSERT INTO public.groups VALUES (232, 'Маг-624', 5);
INSERT INTO public.groups VALUES (233, 'Маг-724', 5);
INSERT INTO public.groups VALUES (234, 'Маг-123', 5);
INSERT INTO public.groups VALUES (235, 'Маг-423', 5);
INSERT INTO public.groups VALUES (236, 'Маг-523', 5);
INSERT INTO public.groups VALUES (237, 'Маг-623', 5);
INSERT INTO public.groups VALUES (238, 'Маг-723', 5);
INSERT INTO public.groups VALUES (239, 'ЭМА-41', 1);
INSERT INTO public.groups VALUES (240, 'ЭМА-42', 1);
INSERT INTO public.groups VALUES (241, 'ЭМ-41', 1);
INSERT INTO public.groups VALUES (242, 'ЭМ-42', 1);
INSERT INTO public.groups VALUES (243, 'ЭМ-43', 1);
INSERT INTO public.groups VALUES (244, 'ЭМ-45', 1);
INSERT INTO public.groups VALUES (245, 'ЭМ-47', 1);
INSERT INTO public.groups VALUES (246, 'ЭМА-31', 1);
INSERT INTO public.groups VALUES (247, 'ЭМА-32', 1);
INSERT INTO public.groups VALUES (248, 'ЭМ-31', 1);
INSERT INTO public.groups VALUES (249, 'ЭМ-32', 1);
INSERT INTO public.groups VALUES (250, 'ЭМ-33', 1);
INSERT INTO public.groups VALUES (251, 'ЭМ-35', 1);
INSERT INTO public.groups VALUES (252, 'ЭМ-37', 1);
INSERT INTO public.groups VALUES (253, 'ЭМА-21', 1);
INSERT INTO public.groups VALUES (254, 'ЭМА-23', 1);
INSERT INTO public.groups VALUES (255, 'ЭМ-21', 1);
INSERT INTO public.groups VALUES (256, 'ЭМ-22', 1);
INSERT INTO public.groups VALUES (257, 'ЭМ-23', 1);
INSERT INTO public.groups VALUES (258, 'ЭМ-25', 1);
INSERT INTO public.groups VALUES (259, 'ЭМА-11', 1);
INSERT INTO public.groups VALUES (260, 'ЭМА-12', 1);
INSERT INTO public.groups VALUES (261, 'ЭМА-13', 1);
INSERT INTO public.groups VALUES (262, 'ЭМ-11', 1);
INSERT INTO public.groups VALUES (263, 'ЭМ-12', 1);
INSERT INTO public.groups VALUES (264, 'ЭМ-13', 1);
INSERT INTO public.groups VALUES (265, 'ЭМ-15', 1);
INSERT INTO public.groups VALUES (266, 'ЭМ-17', 1);
INSERT INTO public.groups VALUES (267, 'ЭММА-41', 1);
INSERT INTO public.groups VALUES (268, 'ЭММА-42', 1);
INSERT INTO public.groups VALUES (269, 'ЭММ-41', 1);
INSERT INTO public.groups VALUES (270, 'ЭММ-42', 1);
INSERT INTO public.groups VALUES (271, 'ЭММ-43', 1);
INSERT INTO public.groups VALUES (272, 'ЭММ-44', 1);
INSERT INTO public.groups VALUES (273, 'ЭММ-45', 1);
INSERT INTO public.groups VALUES (274, 'ЭММ-47', 1);
INSERT INTO public.groups VALUES (275, 'ЭММА-31', 1);
INSERT INTO public.groups VALUES (276, 'ЭММ-31', 1);
INSERT INTO public.groups VALUES (277, 'ЭММ-32', 1);
INSERT INTO public.groups VALUES (278, 'ЭММ-33', 1);
INSERT INTO public.groups VALUES (279, 'ЭММ-34', 1);
INSERT INTO public.groups VALUES (280, 'ЭММ-37', 1);
INSERT INTO public.groups VALUES (281, 'ПМИ-41', 7);
INSERT INTO public.groups VALUES (282, 'ПМИ-42', 7);
INSERT INTO public.groups VALUES (283, 'ПМИ-43', 7);
INSERT INTO public.groups VALUES (284, 'ПМ-41', 7);
INSERT INTO public.groups VALUES (285, 'ПМ-42', 7);
INSERT INTO public.groups VALUES (286, 'ПМ-43', 7);
INSERT INTO public.groups VALUES (287, 'ПМ-44', 7);
INSERT INTO public.groups VALUES (288, 'ПМ-45', 7);
INSERT INTO public.groups VALUES (289, 'ПМИ-31', 7);
INSERT INTO public.groups VALUES (290, 'ПМИ-32', 7);
INSERT INTO public.groups VALUES (291, 'ПМИ-33', 7);
INSERT INTO public.groups VALUES (292, 'ПМ-31', 7);
INSERT INTO public.groups VALUES (293, 'ПМ-32', 7);
INSERT INTO public.groups VALUES (294, 'ПМ-33', 7);
INSERT INTO public.groups VALUES (295, 'ПМ-34', 7);
INSERT INTO public.groups VALUES (296, 'ПМ-35', 7);
INSERT INTO public.groups VALUES (297, 'ПМИ-22', 7);
INSERT INTO public.groups VALUES (298, 'ПМИ-23', 7);
INSERT INTO public.groups VALUES (299, 'ПМ-21', 7);
INSERT INTO public.groups VALUES (300, 'ПМ-23', 7);
INSERT INTO public.groups VALUES (301, 'ПМ-24', 7);
INSERT INTO public.groups VALUES (302, 'ПМ-25', 7);
INSERT INTO public.groups VALUES (303, 'ПМИ-11', 7);
INSERT INTO public.groups VALUES (304, 'ПМИ-12', 7);
INSERT INTO public.groups VALUES (305, 'ПМ-12', 7);
INSERT INTO public.groups VALUES (306, 'ПМ-13', 7);
INSERT INTO public.groups VALUES (307, 'ПМ-14', 7);
INSERT INTO public.groups VALUES (308, 'ПМ-15', 7);
INSERT INTO public.groups VALUES (309, 'ПМИМ-41', 7);
INSERT INTO public.groups VALUES (310, 'ПММ-41', 7);
INSERT INTO public.groups VALUES (311, 'ПММ-42', 7);
INSERT INTO public.groups VALUES (312, 'ПММ-43', 7);
INSERT INTO public.groups VALUES (313, 'ПМИМ-31', 7);
INSERT INTO public.groups VALUES (314, 'ПММ-31', 7);
INSERT INTO public.groups VALUES (315, 'ПММ-32', 7);
INSERT INTO public.groups VALUES (316, 'РКС10-41', 4);
INSERT INTO public.groups VALUES (317, 'РКС10-42', 4);
INSERT INTO public.groups VALUES (318, 'РК6-41', 4);
INSERT INTO public.groups VALUES (319, 'РМ2-41', 4);
INSERT INTO public.groups VALUES (320, 'РН1-41', 4);
INSERT INTO public.groups VALUES (321, 'РН1-42', 4);
INSERT INTO public.groups VALUES (322, 'РП4-41', 4);
INSERT INTO public.groups VALUES (323, 'РП4-42', 4);
INSERT INTO public.groups VALUES (324, 'РТВ14-41', 4);
INSERT INTO public.groups VALUES (325, 'РТВ14-42', 4);
INSERT INTO public.groups VALUES (326, 'РТС9-41', 4);
INSERT INTO public.groups VALUES (327, 'РТС9-42', 4);
INSERT INTO public.groups VALUES (328, 'РТ5-41', 4);
INSERT INTO public.groups VALUES (329, 'РЭ3-41', 4);
INSERT INTO public.groups VALUES (330, 'РЭ3-42', 4);
INSERT INTO public.groups VALUES (331, 'РКС10-31', 4);
INSERT INTO public.groups VALUES (332, 'РК6-31', 4);
INSERT INTO public.groups VALUES (333, 'РМ2-31', 4);
INSERT INTO public.groups VALUES (334, 'РН1-31', 4);
INSERT INTO public.groups VALUES (335, 'РН1-32', 4);
INSERT INTO public.groups VALUES (336, 'РП4-31', 4);
INSERT INTO public.groups VALUES (337, 'РП4-32', 4);
INSERT INTO public.groups VALUES (338, 'РТВ14-31', 4);
INSERT INTO public.groups VALUES (339, 'РТС9-31', 4);
INSERT INTO public.groups VALUES (340, 'РТ5-31', 4);
INSERT INTO public.groups VALUES (341, 'РЭ3-31', 4);
INSERT INTO public.groups VALUES (342, 'РЭ3-32', 4);
INSERT INTO public.groups VALUES (343, 'РКС10-21', 4);
INSERT INTO public.groups VALUES (344, 'РК6-21', 4);
INSERT INTO public.groups VALUES (345, 'РМС7-21', 4);
INSERT INTO public.groups VALUES (346, 'РНТ1-21', 4);
INSERT INTO public.groups VALUES (347, 'РП4-21', 4);
INSERT INTO public.groups VALUES (348, 'РП4-22', 4);
INSERT INTO public.groups VALUES (349, 'РТВ14-21', 4);
INSERT INTO public.groups VALUES (350, 'РТС9-21', 4);
INSERT INTO public.groups VALUES (351, 'РТ5-21', 4);
INSERT INTO public.groups VALUES (352, 'РЭН2-21', 4);
INSERT INTO public.groups VALUES (353, 'РЭ3-21', 4);
INSERT INTO public.groups VALUES (354, 'РЭ3-22', 4);
INSERT INTO public.groups VALUES (355, 'РКС10-11', 4);
INSERT INTO public.groups VALUES (356, 'РК6-11', 4);
INSERT INTO public.groups VALUES (357, 'РМС7-11', 4);
INSERT INTO public.groups VALUES (358, 'РНТ1-11', 4);
INSERT INTO public.groups VALUES (359, 'РП4-11', 4);
INSERT INTO public.groups VALUES (360, 'РТВ14-11', 4);
INSERT INTO public.groups VALUES (361, 'РТС9-11', 4);
INSERT INTO public.groups VALUES (362, 'РТ5-11', 4);
INSERT INTO public.groups VALUES (363, 'РЭН2-11', 4);
INSERT INTO public.groups VALUES (364, 'РЭ3-11', 4);
INSERT INTO public.groups VALUES (365, 'ВШ1-41', 4);
INSERT INTO public.groups VALUES (366, 'ВШ2-41', 4);
INSERT INTO public.groups VALUES (367, 'РКМ-41', 4);
INSERT INTO public.groups VALUES (368, 'РМС-41', 4);
INSERT INTO public.groups VALUES (369, 'РНМ-41', 4);
INSERT INTO public.groups VALUES (370, 'РТИМ-41', 4);
INSERT INTO public.groups VALUES (371, 'РТМ-41', 4);
INSERT INTO public.groups VALUES (372, 'РЭМ-41', 4);
INSERT INTO public.groups VALUES (373, 'РКМ-31', 4);
INSERT INTO public.groups VALUES (374, 'РМС-31', 4);
INSERT INTO public.groups VALUES (375, 'РНМ-31', 4);
INSERT INTO public.groups VALUES (376, 'РТИМ-31', 4);
INSERT INTO public.groups VALUES (377, 'РТМ-31', 4);
INSERT INTO public.groups VALUES (378, 'РЭМ-31', 4);
INSERT INTO public.groups VALUES (379, 'ФГ-41', 8);
INSERT INTO public.groups VALUES (380, 'ФК-41', 8);
INSERT INTO public.groups VALUES (381, 'ФЛ-41', 8);
INSERT INTO public.groups VALUES (382, 'ФТ-41', 8);
INSERT INTO public.groups VALUES (383, 'ФТ-42', 8);
INSERT INTO public.groups VALUES (384, 'ФФ-41', 8);
INSERT INTO public.groups VALUES (385, 'ФГ-31', 8);
INSERT INTO public.groups VALUES (386, 'ФК-31', 8);
INSERT INTO public.groups VALUES (387, 'ФЛ-31', 8);
INSERT INTO public.groups VALUES (388, 'ФТ-31', 8);
INSERT INTO public.groups VALUES (389, 'ФТ-32', 8);
INSERT INTO public.groups VALUES (390, 'ФФ-31', 8);
INSERT INTO public.groups VALUES (391, 'ФГ-21', 8);
INSERT INTO public.groups VALUES (392, 'ФК-21', 8);
INSERT INTO public.groups VALUES (393, 'ФЛ-21', 8);
INSERT INTO public.groups VALUES (394, 'ФТ-21', 8);
INSERT INTO public.groups VALUES (395, 'ФФ-21', 8);
INSERT INTO public.groups VALUES (396, 'ФГ-11', 8);
INSERT INTO public.groups VALUES (397, 'ФК-11', 8);
INSERT INTO public.groups VALUES (398, 'ФЛ-11', 8);
INSERT INTO public.groups VALUES (399, 'ФТ-11', 8);
INSERT INTO public.groups VALUES (400, 'ФФ-11', 8);
INSERT INTO public.groups VALUES (401, 'ФГ-41М', 8);
INSERT INTO public.groups VALUES (402, 'ФЛ-41М', 8);
INSERT INTO public.groups VALUES (403, 'ФО-41М', 8);
INSERT INTO public.groups VALUES (404, 'ФТ-41М', 8);
INSERT INTO public.groups VALUES (405, 'ФТ-42М', 8);
INSERT INTO public.groups VALUES (406, 'ФА-31М', 8);
INSERT INTO public.groups VALUES (407, 'ФГ-31М', 8);
INSERT INTO public.groups VALUES (408, 'ФЛ-31М', 8);
INSERT INTO public.groups VALUES (409, 'ФО-31М', 8);
INSERT INTO public.groups VALUES (410, 'ФТ-31М', 8);
INSERT INTO public.groups VALUES (411, 'EN3-41', 9);
INSERT INTO public.groups VALUES (412, 'ТЭ-41', 9);
INSERT INTO public.groups VALUES (413, 'ЭнБ-41', 9);
INSERT INTO public.groups VALUES (414, 'ЭН1-41', 9);
INSERT INTO public.groups VALUES (415, 'ЭН1-42', 9);
INSERT INTO public.groups VALUES (416, 'ЭН1-45', 9);
INSERT INTO public.groups VALUES (417, 'ЭН2-41', 9);
INSERT INTO public.groups VALUES (418, 'ЭН2-42', 9);
INSERT INTO public.groups VALUES (419, 'ЭН2-44', 9);
INSERT INTO public.groups VALUES (420, 'ЭН2-45', 9);
INSERT INTO public.groups VALUES (421, 'ТЭ-31', 9);
INSERT INTO public.groups VALUES (422, 'ЭнБ-31', 9);
INSERT INTO public.groups VALUES (423, 'ЭН1-31', 9);
INSERT INTO public.groups VALUES (424, 'ЭН1-32', 9);
INSERT INTO public.groups VALUES (425, 'ЭН1-34', 9);
INSERT INTO public.groups VALUES (426, 'ЭН1-35', 9);
INSERT INTO public.groups VALUES (427, 'ЭН2-31', 9);
INSERT INTO public.groups VALUES (428, 'ЭН2-32', 9);
INSERT INTO public.groups VALUES (429, 'ЭН2-35', 9);
INSERT INTO public.groups VALUES (430, 'ТЭ-21', 9);
INSERT INTO public.groups VALUES (431, 'ЭнБ-21', 9);
INSERT INTO public.groups VALUES (432, 'ЭН1-21', 9);
INSERT INTO public.groups VALUES (433, 'ЭН1-22', 9);
INSERT INTO public.groups VALUES (434, 'ЭН1-25', 9);
INSERT INTO public.groups VALUES (435, 'ЭН2-21', 9);
INSERT INTO public.groups VALUES (436, 'ЭН2-22', 9);
INSERT INTO public.groups VALUES (437, 'ЭН2-25', 9);
INSERT INTO public.groups VALUES (438, 'ТЭ-11', 9);
INSERT INTO public.groups VALUES (439, 'ЭнБ-11', 9);
INSERT INTO public.groups VALUES (440, 'ЭН1-11', 9);
INSERT INTO public.groups VALUES (441, 'ЭН1-12', 9);
INSERT INTO public.groups VALUES (442, 'ЭН1-13у', 9);
INSERT INTO public.groups VALUES (443, 'ЭН1-15', 9);
INSERT INTO public.groups VALUES (444, 'ЭН2-11', 9);
INSERT INTO public.groups VALUES (445, 'ЭН2-15', 9);
INSERT INTO public.groups VALUES (446, 'ТЭМ-41', 9);
INSERT INTO public.groups VALUES (447, 'ЭнБМ-41', 9);
INSERT INTO public.groups VALUES (448, 'ЭНМЭ-41', 9);
INSERT INTO public.groups VALUES (449, 'ЭНМ1-41', 9);
INSERT INTO public.groups VALUES (450, 'ЭНМ1-42', 9);
INSERT INTO public.groups VALUES (451, 'ЭНМ1-44', 9);
INSERT INTO public.groups VALUES (452, 'ЭНМ2-41', 9);
INSERT INTO public.groups VALUES (453, 'ЭНМ2-43', 9);
INSERT INTO public.groups VALUES (454, 'ТЭМ-31', 9);
INSERT INTO public.groups VALUES (455, 'ЭнБМ-31', 9);
INSERT INTO public.groups VALUES (456, 'ЭНМЭ-31', 9);
INSERT INTO public.groups VALUES (457, 'ЭНМ1-31', 9);
INSERT INTO public.groups VALUES (458, 'ЭНМ1-32', 9);
INSERT INTO public.groups VALUES (459, 'ЭНМ1-34', 9);
INSERT INTO public.groups VALUES (460, 'ЭНМ2-31', 9);
INSERT INTO public.groups VALUES (461, 'ЭНМ2-33', 9);
INSERT INTO public.groups VALUES (462, 'ФБИ-41', 2);
INSERT INTO public.groups VALUES (463, 'ФБИ-42', 2);
INSERT INTO public.groups VALUES (464, 'ФБИ-43', 2);
INSERT INTO public.groups VALUES (465, 'ФБИ-44', 2);
INSERT INTO public.groups VALUES (466, 'ФБМТ-41', 2);
INSERT INTO public.groups VALUES (467, 'ФБТХ-41', 2);
INSERT INTO public.groups VALUES (468, 'ФБТХ-42', 2);
INSERT INTO public.groups VALUES (469, 'ФБЭБС-41', 2);
INSERT INTO public.groups VALUES (470, 'ФБЭБС-42', 2);
INSERT INTO public.groups VALUES (471, 'ФБЭБС-43', 2);
INSERT INTO public.groups VALUES (472, 'ФБЭ-41', 2);
INSERT INTO public.groups VALUES (473, 'ФБЭ-42', 2);
INSERT INTO public.groups VALUES (474, 'ФБЭ-43', 2);
INSERT INTO public.groups VALUES (475, 'ФБЭ-44', 2);
INSERT INTO public.groups VALUES (476, 'ФБЭ-45', 2);
INSERT INTO public.groups VALUES (477, 'ФБ-41', 2);
INSERT INTO public.groups VALUES (478, 'ФБ-42', 2);
INSERT INTO public.groups VALUES (479, 'ФБ-43', 2);
INSERT INTO public.groups VALUES (480, 'ФБ-44', 2);
INSERT INTO public.groups VALUES (481, 'ФБ-45', 2);
INSERT INTO public.groups VALUES (482, 'ЭК-41', 2);
INSERT INTO public.groups VALUES (483, 'ЭК-42', 2);
INSERT INTO public.groups VALUES (484, 'ФБИ-31', 2);
INSERT INTO public.groups VALUES (485, 'ФБИ-32', 2);
INSERT INTO public.groups VALUES (486, 'ФБИ-33', 2);
INSERT INTO public.groups VALUES (487, 'ФБИ-34', 2);
INSERT INTO public.groups VALUES (488, 'ФБк-31', 2);
INSERT INTO public.groups VALUES (489, 'ФБМТ-31', 2);
INSERT INTO public.groups VALUES (490, 'ФБТХ-31', 2);
INSERT INTO public.groups VALUES (491, 'ФБТХ-32', 2);
INSERT INTO public.groups VALUES (492, 'ФБЭБС-31', 2);
INSERT INTO public.groups VALUES (493, 'ФБЭБС-32', 2);
INSERT INTO public.groups VALUES (494, 'ФБЭБС-33', 2);
INSERT INTO public.groups VALUES (495, 'ФБЭ-31', 2);
INSERT INTO public.groups VALUES (496, 'ФБЭ-32', 2);
INSERT INTO public.groups VALUES (497, 'ФБЭ-33', 2);
INSERT INTO public.groups VALUES (498, 'ФБЭ-34', 2);
INSERT INTO public.groups VALUES (499, 'ФБ-31', 2);
INSERT INTO public.groups VALUES (500, 'ФБ-32', 2);
INSERT INTO public.groups VALUES (501, 'ФБ-33', 2);
INSERT INTO public.groups VALUES (502, 'ФБ-34', 2);
INSERT INTO public.groups VALUES (503, 'ФБ-35', 2);
INSERT INTO public.groups VALUES (504, 'ЭК-31', 2);
INSERT INTO public.groups VALUES (505, 'ФБИ-21', 2);
INSERT INTO public.groups VALUES (506, 'ФБИ-22', 2);
INSERT INTO public.groups VALUES (507, 'ФБИ-23', 2);
INSERT INTO public.groups VALUES (508, 'ФБИ-24', 2);
INSERT INTO public.groups VALUES (509, 'ФБМТ-21', 2);
INSERT INTO public.groups VALUES (510, 'ФБТХ-21', 2);
INSERT INTO public.groups VALUES (511, 'ФБТХ-22', 2);
INSERT INTO public.groups VALUES (512, 'ФБЭБС-21', 2);
INSERT INTO public.groups VALUES (513, 'ФБЭБС-22', 2);
INSERT INTO public.groups VALUES (514, 'ФБЭБС-23', 2);
INSERT INTO public.groups VALUES (515, 'ФБЭ-21', 2);
INSERT INTO public.groups VALUES (516, 'ФБЭ-23', 2);
INSERT INTO public.groups VALUES (517, 'ФБЭ-24', 2);
INSERT INTO public.groups VALUES (518, 'ФБ-21', 2);
INSERT INTO public.groups VALUES (519, 'ФБ-22', 2);
INSERT INTO public.groups VALUES (520, 'ФБ-23', 2);
INSERT INTO public.groups VALUES (521, 'ФБ-24', 2);
INSERT INTO public.groups VALUES (522, 'ФБ-25', 2);
INSERT INTO public.groups VALUES (523, 'ФБ-26', 2);
INSERT INTO public.groups VALUES (524, 'ЭК-21', 2);
INSERT INTO public.groups VALUES (525, 'ФБИ-11', 2);
INSERT INTO public.groups VALUES (526, 'ФБИ-12', 2);
INSERT INTO public.groups VALUES (527, 'ФБИ-13', 2);
INSERT INTO public.groups VALUES (528, 'ФБИ-14', 2);
INSERT INTO public.groups VALUES (529, 'ФБМИП-11', 2);
INSERT INTO public.groups VALUES (530, 'ФБМТ-11', 2);
INSERT INTO public.groups VALUES (531, 'ФБТХ-11', 2);
INSERT INTO public.groups VALUES (532, 'ФБТХ-12', 2);
INSERT INTO public.groups VALUES (533, 'ФБЭБС-11', 2);
INSERT INTO public.groups VALUES (534, 'ФБЭБС-12', 2);
INSERT INTO public.groups VALUES (535, 'ФБЭБС-13', 2);
INSERT INTO public.groups VALUES (536, 'ФБЭ-11', 2);
INSERT INTO public.groups VALUES (537, 'ФБЭ-13', 2);
INSERT INTO public.groups VALUES (538, 'ФБЭ-14', 2);
INSERT INTO public.groups VALUES (539, 'ФБ-11', 2);
INSERT INTO public.groups VALUES (540, 'ФБ-12', 2);
INSERT INTO public.groups VALUES (541, 'ФБ-13', 2);
INSERT INTO public.groups VALUES (542, 'ФБ-14', 2);
INSERT INTO public.groups VALUES (543, 'ФБ-15', 2);
INSERT INTO public.groups VALUES (544, 'ФБ-16', 2);
INSERT INTO public.groups VALUES (545, 'ФБ-17', 2);
INSERT INTO public.groups VALUES (546, 'ЭК-11', 2);
INSERT INTO public.groups VALUES (547, 'ФБЭБС-01', 2);
INSERT INTO public.groups VALUES (548, 'ФБЭБС-02', 2);
INSERT INTO public.groups VALUES (549, 'дФБМ-44', 2);
INSERT INTO public.groups VALUES (550, 'дФБМ-45', 2);
INSERT INTO public.groups VALUES (551, 'дФБМ-46', 2);
INSERT INTO public.groups VALUES (552, 'дФБМ-47', 2);
INSERT INTO public.groups VALUES (553, 'ФБМ-41', 2);
INSERT INTO public.groups VALUES (554, 'ФБМ-42', 2);
INSERT INTO public.groups VALUES (555, 'ФБМ-43', 2);
INSERT INTO public.groups VALUES (556, 'ФБТХМ-41', 2);
INSERT INTO public.groups VALUES (557, 'ФБЭМ-45', 2);
INSERT INTO public.groups VALUES (558, 'ФБЭМ-46', 2);
INSERT INTO public.groups VALUES (559, 'дФБМ-34', 2);
INSERT INTO public.groups VALUES (560, 'дФБМ-35', 2);
INSERT INTO public.groups VALUES (561, 'дФБМ-36', 2);
INSERT INTO public.groups VALUES (562, 'ФБМ-31', 2);
INSERT INTO public.groups VALUES (563, 'ФБМ-32', 2);
INSERT INTO public.groups VALUES (564, 'ФБМ-33', 2);
INSERT INTO public.groups VALUES (565, 'ФБТХМ-31', 2);
INSERT INTO public.groups VALUES (566, 'ФБЭМ-35', 2);
INSERT INTO public.groups VALUES (567, 'ФБЭМ-36', 2);
INSERT INTO public.groups VALUES (568, 'ИЯ-41', 10);
INSERT INTO public.groups VALUES (569, 'ИЯ-42', 10);
INSERT INTO public.groups VALUES (570, 'ИЯ-43', 10);
INSERT INTO public.groups VALUES (571, 'ИЯ-44', 10);
INSERT INTO public.groups VALUES (572, 'ИЯ-45', 10);
INSERT INTO public.groups VALUES (573, 'П-41', 10);
INSERT INTO public.groups VALUES (574, 'П-42', 10);
INSERT INTO public.groups VALUES (575, 'П-43', 10);
INSERT INTO public.groups VALUES (576, 'П-44', 10);
INSERT INTO public.groups VALUES (577, 'РГ-41', 10);
INSERT INTO public.groups VALUES (578, 'РГ-42', 10);
INSERT INTO public.groups VALUES (579, 'РГ-43', 10);
INSERT INTO public.groups VALUES (580, 'РГ-45', 10);
INSERT INTO public.groups VALUES (581, 'СЛ-41', 10);
INSERT INTO public.groups VALUES (582, 'СЛ-42', 10);
INSERT INTO public.groups VALUES (583, 'СЛ-43', 10);
INSERT INTO public.groups VALUES (584, 'Ф-41', 10);
INSERT INTO public.groups VALUES (585, 'Ф-42', 10);
INSERT INTO public.groups VALUES (586, 'Ф-43', 10);
INSERT INTO public.groups VALUES (587, 'Ф-44', 10);
INSERT INTO public.groups VALUES (588, 'ИЯ-31', 10);
INSERT INTO public.groups VALUES (589, 'ИЯ-32', 10);
INSERT INTO public.groups VALUES (590, 'ИЯ-33', 10);
INSERT INTO public.groups VALUES (591, 'ИЯ-34', 10);
INSERT INTO public.groups VALUES (592, 'ИЯ-35', 10);
INSERT INTO public.groups VALUES (593, 'П-31', 10);
INSERT INTO public.groups VALUES (594, 'П-32', 10);
INSERT INTO public.groups VALUES (595, 'П-33', 10);
INSERT INTO public.groups VALUES (596, 'П-35', 10);
INSERT INTO public.groups VALUES (597, 'РГ-31', 10);
INSERT INTO public.groups VALUES (598, 'РГ-32', 10);
INSERT INTO public.groups VALUES (599, 'РГ-33', 10);
INSERT INTO public.groups VALUES (600, 'РГ-35', 10);
INSERT INTO public.groups VALUES (601, 'СЛ-31', 10);
INSERT INTO public.groups VALUES (602, 'СЛ-32', 10);
INSERT INTO public.groups VALUES (603, 'СЛ-33', 10);
INSERT INTO public.groups VALUES (604, 'Ф-31', 10);
INSERT INTO public.groups VALUES (605, 'Ф-32', 10);
INSERT INTO public.groups VALUES (606, 'Ф-33', 10);
INSERT INTO public.groups VALUES (607, 'ИЯ-21', 10);
INSERT INTO public.groups VALUES (608, 'ИЯ-22', 10);
INSERT INTO public.groups VALUES (609, 'ИЯ-23', 10);
INSERT INTO public.groups VALUES (610, 'ИЯ-24', 10);
INSERT INTO public.groups VALUES (611, 'ИЯ-25', 10);
INSERT INTO public.groups VALUES (612, 'ИЯ-26', 10);
INSERT INTO public.groups VALUES (613, 'П-21', 10);
INSERT INTO public.groups VALUES (614, 'П-22', 10);
INSERT INTO public.groups VALUES (615, 'П-23', 10);
INSERT INTO public.groups VALUES (616, 'РГ-21', 10);
INSERT INTO public.groups VALUES (617, 'РГ-22', 10);
INSERT INTO public.groups VALUES (618, 'РГ-23', 10);
INSERT INTO public.groups VALUES (619, 'РГ-25', 10);
INSERT INTO public.groups VALUES (620, 'СЛ-21', 10);
INSERT INTO public.groups VALUES (621, 'СЛ-22', 10);
INSERT INTO public.groups VALUES (622, 'СЛ-23', 10);
INSERT INTO public.groups VALUES (623, 'Ф-21', 10);
INSERT INTO public.groups VALUES (624, 'Ф-23', 10);
INSERT INTO public.groups VALUES (625, 'ИЯ-11', 10);
INSERT INTO public.groups VALUES (626, 'ИЯ-12', 10);
INSERT INTO public.groups VALUES (627, 'ИЯ-13', 10);
INSERT INTO public.groups VALUES (628, 'ИЯ-15', 10);
INSERT INTO public.groups VALUES (629, 'ИЯ-16', 10);
INSERT INTO public.groups VALUES (630, 'П-11', 10);
INSERT INTO public.groups VALUES (631, 'П-12', 10);
INSERT INTO public.groups VALUES (632, 'П-13', 10);
INSERT INTO public.groups VALUES (633, 'РГ-11', 10);
INSERT INTO public.groups VALUES (634, 'РГ-13', 10);
INSERT INTO public.groups VALUES (635, 'РГ-15', 10);
INSERT INTO public.groups VALUES (636, 'СЛ-11', 10);
INSERT INTO public.groups VALUES (637, 'СЛ-12', 10);
INSERT INTO public.groups VALUES (638, 'СЛ-13', 10);
INSERT INTO public.groups VALUES (639, 'Ф-11', 10);
INSERT INTO public.groups VALUES (640, 'Ф-13', 10);
INSERT INTO public.groups VALUES (641, 'ПлМ-41', 10);
INSERT INTO public.groups VALUES (642, 'ПОм-41', 10);
INSERT INTO public.groups VALUES (643, 'ПОм-42', 10);
INSERT INTO public.groups VALUES (644, 'РГМ-41', 10);
INSERT INTO public.groups VALUES (645, 'СЛМ-41', 10);
INSERT INTO public.groups VALUES (646, 'ПлМ-31', 10);
INSERT INTO public.groups VALUES (647, 'ПЛМ-32', 10);
INSERT INTO public.groups VALUES (648, 'ПОм-31', 10);
INSERT INTO public.groups VALUES (649, 'ПОм-32', 10);
INSERT INTO public.groups VALUES (650, 'РГМ-31', 10);
INSERT INTO public.groups VALUES (651, 'СЛМ-31', 10);
INSERT INTO public.groups VALUES (652, 'Фм-31', 10);
INSERT INTO public.groups VALUES (653, 'ДЭ-430', 13);
INSERT INTO public.groups VALUES (654, 'ДЭ-460', 13);
INSERT INTO public.groups VALUES (655, 'ЗФ-424', 13);
INSERT INTO public.groups VALUES (656, 'ДЭ-330', 13);
INSERT INTO public.groups VALUES (657, 'ДЭ-360', 13);
INSERT INTO public.groups VALUES (658, 'ЗФ-324', 13);
INSERT INTO public.groups VALUES (659, 'ДЭ-230', 13);
INSERT INTO public.groups VALUES (660, 'ДЭ-260', 13);
INSERT INTO public.groups VALUES (661, 'ЗФ-224', 13);
INSERT INTO public.groups VALUES (662, 'ДГ-110', 13);
INSERT INTO public.groups VALUES (663, 'ДЭ-130', 13);
INSERT INTO public.groups VALUES (664, 'ДЭ-160', 13);
INSERT INTO public.groups VALUES (665, 'ЗФ-124', 13);
INSERT INTO public.groups VALUES (666, 'КН-41', 21);
INSERT INTO public.groups VALUES (667, 'КН-42', 21);
INSERT INTO public.groups VALUES (668, 'ПСФ-41', 21);
INSERT INTO public.groups VALUES (669, 'ПСФ-42', 21);
INSERT INTO public.groups VALUES (670, 'СР-41', 21);
INSERT INTO public.groups VALUES (671, 'КН-31', 21);
INSERT INTO public.groups VALUES (672, 'ПСФ-31', 21);
INSERT INTO public.groups VALUES (673, 'ПСФ-32', 21);
INSERT INTO public.groups VALUES (674, 'СР-31', 21);
INSERT INTO public.groups VALUES (675, 'КН-21', 21);
INSERT INTO public.groups VALUES (676, 'КН-22', 21);
INSERT INTO public.groups VALUES (677, 'ПСФ-21', 21);
INSERT INTO public.groups VALUES (678, 'ПСФ-22', 21);
INSERT INTO public.groups VALUES (679, 'СР-21', 21);
INSERT INTO public.groups VALUES (680, 'КН-11', 21);
INSERT INTO public.groups VALUES (681, 'КН-12', 21);
INSERT INTO public.groups VALUES (682, 'ПСФ-11', 21);
INSERT INTO public.groups VALUES (683, 'ПСФ-12', 21);
INSERT INTO public.groups VALUES (684, 'СР-11', 21);
INSERT INTO public.groups VALUES (685, 'СРМ-41', 21);
INSERT INTO public.groups VALUES (686, 'АФ-41', 21);
INSERT INTO public.groups VALUES (687, 'Б-41', 21);
INSERT INTO public.groups VALUES (688, 'Б-42', 21);
INSERT INTO public.groups VALUES (689, 'Д-42', 21);
INSERT INTO public.groups VALUES (690, 'Д-45', 21);
INSERT INTO public.groups VALUES (691, 'ИП-41', 21);
INSERT INTO public.groups VALUES (692, 'ИП-42', 21);
INSERT INTO public.groups VALUES (693, 'ИП-43', 21);
INSERT INTO public.groups VALUES (694, 'К-41', 21);
INSERT INTO public.groups VALUES (695, 'П-41', 21);
INSERT INTO public.groups VALUES (696, 'С-41', 21);
INSERT INTO public.groups VALUES (697, 'АФ-31', 21);
INSERT INTO public.groups VALUES (698, 'Б-31', 21);
INSERT INTO public.groups VALUES (699, 'Б-32', 21);
INSERT INTO public.groups VALUES (700, 'Д-32', 21);
INSERT INTO public.groups VALUES (701, 'Д-35', 21);
INSERT INTO public.groups VALUES (702, 'ИП-31', 21);
INSERT INTO public.groups VALUES (703, 'ИП-32', 21);
INSERT INTO public.groups VALUES (704, 'ИП-33', 21);
INSERT INTO public.groups VALUES (705, 'ИП-34', 21);
INSERT INTO public.groups VALUES (706, 'К-31', 21);
INSERT INTO public.groups VALUES (707, 'П-31', 21);
INSERT INTO public.groups VALUES (708, 'С-31', 21);
INSERT INTO public.groups VALUES (709, 'АФ-21', 21);
INSERT INTO public.groups VALUES (710, 'Б-21', 21);
INSERT INTO public.groups VALUES (711, 'Б-22', 21);
INSERT INTO public.groups VALUES (712, 'Д-25', 21);
INSERT INTO public.groups VALUES (713, 'ИП-21', 21);
INSERT INTO public.groups VALUES (714, 'ИП-22', 21);
INSERT INTO public.groups VALUES (715, 'ИП-23', 21);
INSERT INTO public.groups VALUES (716, 'ИС-22', 21);
INSERT INTO public.groups VALUES (717, 'К-21', 21);
INSERT INTO public.groups VALUES (718, 'П-21', 21);
INSERT INTO public.groups VALUES (719, 'С-21', 21);
INSERT INTO public.groups VALUES (720, 'АФ-11', 21);
INSERT INTO public.groups VALUES (721, 'Д-12', 21);
INSERT INTO public.groups VALUES (722, 'Д-15', 21);
INSERT INTO public.groups VALUES (723, 'П-11', 21);
INSERT INTO public.groups VALUES (724, 'С-11', 21);


--
-- TOC entry 3432 (class 0 OID 16526)
-- Dependencies: 232
-- Data for Name: rooms; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3433 (class 0 OID 16531)
-- Dependencies: 233
-- Data for Name: shedule; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3424 (class 0 OID 16499)
-- Dependencies: 224
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3430 (class 0 OID 16520)
-- Dependencies: 230
-- Data for Name: teachers; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3426 (class 0 OID 16507)
-- Dependencies: 226
-- Data for Name: times; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3420 (class 0 OID 16487)
-- Dependencies: 220
-- Data for Name: weeks; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3439 (class 0 OID 0)
-- Dependencies: 221
-- Name: days_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.days_id_seq', 1, false);


--
-- TOC entry 3440 (class 0 OID 0)
-- Dependencies: 227
-- Name: disciplines_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.disciplines_id_seq', 1, false);


--
-- TOC entry 3441 (class 0 OID 0)
-- Dependencies: 215
-- Name: faculties_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.faculties_id_seq', 1, false);


--
-- TOC entry 3442 (class 0 OID 0)
-- Dependencies: 217
-- Name: groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.groups_id_seq', 1, false);


--
-- TOC entry 3443 (class 0 OID 0)
-- Dependencies: 231
-- Name: rooms_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rooms_id_seq', 1, false);


--
-- TOC entry 3444 (class 0 OID 0)
-- Dependencies: 223
-- Name: students_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.students_id_seq', 1, false);


--
-- TOC entry 3445 (class 0 OID 0)
-- Dependencies: 229
-- Name: teachers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teachers_id_seq', 1, false);


--
-- TOC entry 3446 (class 0 OID 0)
-- Dependencies: 225
-- Name: times_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.times_id_seq', 1, false);


--
-- TOC entry 3447 (class 0 OID 0)
-- Dependencies: 219
-- Name: weeks_num_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.weeks_num_seq', 1, false);


--
-- TOC entry 3248 (class 2606 OID 16474)
-- Name: faculties UQ_Faculty_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.faculties
    ADD CONSTRAINT "UQ_Faculty_name" UNIQUE (title) INCLUDE (title);


--
-- TOC entry 3256 (class 2606 OID 16497)
-- Name: days days_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.days
    ADD CONSTRAINT days_pkey PRIMARY KEY (id);


--
-- TOC entry 3262 (class 2606 OID 16517)
-- Name: disciplines disciplines_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplines
    ADD CONSTRAINT disciplines_pkey PRIMARY KEY (id);


--
-- TOC entry 3250 (class 2606 OID 16472)
-- Name: faculties faculties_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.faculties
    ADD CONSTRAINT faculties_pkey PRIMARY KEY (id);


--
-- TOC entry 3252 (class 2606 OID 16480)
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3266 (class 2606 OID 16530)
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- TOC entry 3268 (class 2606 OID 16537)
-- Name: shedule shedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shedule
    ADD CONSTRAINT shedule_pkey PRIMARY KEY (id);


--
-- TOC entry 3258 (class 2606 OID 16505)
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- TOC entry 3264 (class 2606 OID 16524)
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);


--
-- TOC entry 3260 (class 2606 OID 16511)
-- Name: times times_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.times
    ADD CONSTRAINT times_pkey PRIMARY KEY (id);


--
-- TOC entry 3254 (class 2606 OID 16491)
-- Name: weeks weeks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.weeks
    ADD CONSTRAINT weeks_pkey PRIMARY KEY (num);


--
-- TOC entry 3270 (class 2606 OID 16545)
-- Name: disciplines FK_disciplines_teachers; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disciplines
    ADD CONSTRAINT "FK_disciplines_teachers" FOREIGN KEY (id_teacher) REFERENCES public.teachers(id) NOT VALID;


--
-- TOC entry 3269 (class 2606 OID 16481)
-- Name: groups FK_groups_faculties; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT "FK_groups_faculties" FOREIGN KEY (id_faculty) REFERENCES public.faculties(id) NOT VALID;


--
-- TOC entry 3271 (class 2606 OID 16538)
-- Name: shedule FK_shedule_days; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shedule
    ADD CONSTRAINT "FK_shedule_days" FOREIGN KEY (id_day) REFERENCES public.days(id) NOT VALID;


-- Completed on 2024-10-03 09:09:32 UTC

--
-- PostgreSQL database dump complete
--

